language: python
python:
  - "2.7"

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install -U pip pytest
  - pip install -U .

script:
  - python setup.py test

notifications:
  email:
    - noah.hoffman@gmail.com
